include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- components/**/test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
- graphql-schema_comparator
- minitest-profile
- minitest-rails
- minitest-reporters
domains: []
reporters:
- rubocop
- require_not_found
require_paths: []
plugins: []
max_files: 50000
